server:
  port: 8000
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:product_db
    driver-class-name: org.h2.Driver
    username: aluno
    password: segredo
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    url: jdbc:h2:mem:product_db
    schemas: product_db
    user: aluno
    password: segredo